### ISSUE TITLE
Cannot change GUI scale to Large specifically

### ISSUE THREAD

**Issue by Herbadableh** [MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack#5]
When changing the GUI scale in the video settings, the Large scale simply keeps the Normal scale. This occurs even when there are No Mods Loaded. Adding Optifine only makes it skip over Large and Small. If there is an option for this, what is it and how do I change it?
 Normal scale
![image](https://github.com/MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack/assets/34965722/31a05fc1-d656-463b-8ece-f7eefe2e14da)
Large Scale
![image](https://github.com/MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack/assets/34965722/92bcee37-5c33-4675-9e14-5acd7e9b932e)
Mod list
![image](https://github.com/MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack/assets/34965722/71354850-7405-4472-85f3-1fa15bfa833f)

**Comment by Lubang-SF** [comment]
In my understanding, this issue is not a problem with our packs.You can try using: [scaling guis](https://www.curseforge.com/minecraft/mc-mods/scalingguis) or [tip the scales](https://www.curseforge.com/minecraft/mc-mods/tipthescales). But we haven't tested this mod and can't guarantee that it will solve the problem.Also they may conflict with this pack.I hope that helps.
